### ISSUE TITLE
It is possible to open the notation file two times

### ISSUE THREAD

**Issue by eneufeld** [eclipse-emfcloud/coffee-editor#260]
You can open the coffee notation twice by opening it from the tree and the file explorer. 

They are still synced between tree and graphical but the two graphical editors are not synced. I would imagine the easiest fix would be to simply avoid opening the same diagram twice.

**Comment by eneufeld** [comment]
@tortmayr is there a way to block opening the glsp editor a second time for the same file?

**Comment by tortmayr** [comment]
Yes, this can be done. However, this issue sounds like a Theia misconfiguration to me. The Theia Openerservice normally prevents opening multiple editors for one file and reuses the existing editor.

**Comment by sgraband** [comment]
Seems to be fixed. Can be closed together with #457 if no objections.
