### ISSUE TITLE
Palette disabling

### ISSUE THREAD

**Issue by eneufeld** [eclipse-emfcloud/coffee-editor#297]
Disabling a palette tool can be difficult:

- Select an item in the palette. The mouse cursor changes to reflect the active tool
- Press esc: nothing happens (Tool remains active)
- Click in the diagram then press esc: tool is deactivated

The user needs to click at least once in the diagram to disable an active tool, which is not great. Moreover, if the tool is a Node, this will create an element (So you actually need to create the node before being able to cancel the active palette tool).

**Comment by tortmayr** [comment]
:+1:  I openend eclipse-glsp/glsp/issues/110 to fix this directly in GLSP.
