### ISSUE TITLE
Snapshot failure

### ISSUE THREAD

**Issue by ExperimentCloud** [eclipse-emfcloud/coffee-editor#327]
com.eclipsesource.workflow.glsp.server 0.0.1-SNAPSHOT FAILURE
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project com.eclipsesource.workflow.glsp.server: Compilation failure: Compilation failure: 
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/model/WorkflowModelServerAccess.java:[34,35] package org.eclipse.emf.edit.domain does not exist
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/model/WorkflowModelServerAccess.java:[35,35] package org.eclipse.emf.edit.domain does not exist
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/model/WorkflowModelServerAccess.java:[66,17] cannot find symbol
[ERROR]   symbol:   class EditingDomain
[ERROR]   location: class com.eclipsesource.workflow.glsp.server.model.WorkflowModelServerAccess
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/model/WorkflowModelServerAccess.java:[195,16] cannot find symbol
[ERROR]   symbol:   class EditingDomain
[ERROR]   location: class com.eclipsesource.workflow.glsp.server.model.WorkflowModelServerAccess
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/handler/operation/AbstractCreateNodeHandler.java:[19,36] package org.eclipse.emf.edit.command does not exist
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/handler/operation/AbstractCreateEdgeHandler.java:[17,36] package org.eclipse.emf.edit.command does not exist
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/handler/operation/ApplyLabelEditOperationHandler.java:[17,36] package org.eclipse.emf.edit.command does not exist
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/model/WorkflowModelServerSubscriptionListener.java:[25,35] package org.eclipse.emf.edit.domain does not exist
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/model/WorkflowModelServerSubscriptionListener.java:[116,48] cannot find symbol
[ERROR]   symbol:   class EditingDomain
[ERROR]   location: class com.eclipsesource.workflow.glsp.server.model.WorkflowModelServerSubscriptionListener
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/WorkflowGLSPModule.java:[14,37] package org.eclipse.emf.edit.provider does not exist
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/model/WorkflowModelServerAccess.java:[75,42] cannot find symbol
[ERROR]   symbol:   class AdapterFactoryEditingDomain
[ERROR]   location: class com.eclipsesource.workflow.glsp.server.model.WorkflowModelServerAccess
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/handler/operation/AbstractCreateNodeHandler.java:[51,38] cannot find symbol
[ERROR]   symbol:   variable AddCommand
[ERROR]   location: class com.eclipsesource.workflow.glsp.server.handler.operation.AbstractCreateNodeHandler
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/handler/operation/AbstractCreateEdgeHandler.java:[50,38] cannot find symbol
[ERROR]   symbol:   variable AddCommand
[ERROR]   location: class com.eclipsesource.workflow.glsp.server.handler.operation.AbstractCreateEdgeHandler
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/handler/operation/ApplyLabelEditOperationHandler.java:[45,38] cannot find symbol
[ERROR]   symbol:   variable SetCommand
[ERROR]   location: class com.eclipsesource.workflow.glsp.server.handler.operation.ApplyLabelEditOperationHandler
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/model/WorkflowModelServerSubscriptionListener.java:[65,25] cannot find symbol
[ERROR]   symbol:   class EditingDomain
[ERROR]   location: class com.eclipsesource.workflow.glsp.server.model.WorkflowModelServerSubscriptionListener
[ERROR] /Users/Experiment/Desktop/TestCoffee/coffee-editor/backend/plugins/com.eclipsesource.workflow.glsp.server/src/main/java/com/eclipsesource/workflow/glsp/server/WorkflowGLSPModule.java:[125,59] cannot find symbol
[ERROR]   symbol:   class ComposedAdapterFactory
[ERROR]   location: class com.eclipsesource.workflow.glsp.server.WorkflowGLSPModule
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by eneufeld** [comment]
Thank you for the report. We are fixing the example, see https://github.com/eclipse-emfcloud/coffee-editor/pull/328
