### ISSUE TITLE
Improve run.sh error handling

### ISSUE THREAD

**Issue by sgraband** [eclipse-emfcloud/coffee-editor#341]
Currently when a subtask (like the backend build) of the `./run.sh` script is failing, the script is still continuing and starting the application, which may fail.

The failure is then hard to catch as there is no feedback, that a specific task failed. 

Maybe the script should just fail, when one subtask fails to avoid confusion.

**Comment by eneufeld** [comment]
Fixed via https://github.com/eclipse-emfcloud/coffee-editor/commit/d1fb4d46c515fd06481b6dfa64a9f007addd0db9
