### ISSUE TITLE
Auto Layout action in the workflow diagram has no effect

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-emfcloud/coffee-editor#351]
You can click it in the diagram menu, but it has not effect

**Comment by eneufeld** [comment]
@tortmayr @ndoschek do you have an idea what this might be caused by?

**Comment by tortmayr** [comment]
I had a quick look, however I'm not that familiar with the model-server specific LayoutEngine (ESMLayoutEngine) so maybe  @ndoschek can provide more insights on this.

**Comment by ndoschek** [comment]
By merging #419 this should be fixed (during the former update process I fixed that). Also, on current master the auto layout works for me via keyboard shortcut as well as the menu entry.

**Comment by eneufeld** [comment]
I double check, maybe something was off for me yesterday.

**Comment by eneufeld** [comment]
Works!
Fixed by #419
