### ISSUE TITLE
Install Issues on Windows with run.sh

### ISSUE THREAD

**Issue by brettforbes** [eclipse-emfcloud/coffee-editor#359]
I have followed the instructions in the readme, so Java is installed, node is already install with yarn, and i install maven and setup the paths.

After cloning the repo, and cd-ing into the directory, when i run ```run.sh```, I get a Windows popup asking me to select the application to run the file with.

What should i do?

![image](https://user-images.githubusercontent.com/24556510/116766837-ee3d0400-aa6f-11eb-8191-cc8158d58484.png)

**Comment by eneufeld** [comment]
Hi @brettforbes, 
you can't run the `run.sh` on windows.
You need to run the different commands manually on windows at the moment.
That would be:
- build backend: `backend/releng/org.eclipse.emfcloud.coffee.parent/` then `mvn clean install`
- copy backend:
  - `backend/releng/org.eclipse.emfcloud.coffee.product/target/products/org.eclipse.emfcloud.coffee.product.codegen/win32\win32/x86_64` to `web/coffee-java-extension/server`
  - `backend/releng/org.eclipse.emfcloud.coffee.product/target/products/org.eclipse.emfcloud.coffee.product.workflow.analyzer/win32\win32/x86_64` to `web/coffee-workflow-analyzer/server`
  - `backend/releng/org.eclipse.emfcloud.coffee.product/target/products/org.eclipse.emfcloud.coffee.product.workflow.dsl/win32\win32/x86_64` to `web/coffee-workflow-analyzer-editors/server`
  - `backend/releng/org.eclipse.emfcloud.coffee.product/target/products/org.eclipse.emfcloud.coffee.product.workflow.glsp.server/win32\win32/x86_64` to `web/coffee-server/server/glsp`
  - `backend/releng/org.eclipse.emfcloud.coffee.product/target/products/org.eclipse.emfcloud.coffee.product.modelserver/win32\win32/x86_64` to `web/coffee-server/server/model`
- build frontend: `cd web` then `yarn`
- run application: `cd web/browser-app` then `yarn start --hostname 0.0.0.0`

Alternatively you could try using the Git Bash to run the `run.sh` file. 

We plan on improving the experience on windows in the future. Sorry for this inconvenience in the mean time.

**Comment by brettforbes** [comment]
Hi Eugene,

Thanks for the detailed response, brilliant.

Before I start, would it be better to install https://cmder.net/ and then use it to run the shell command?

If so, this is an easy thing for Win 10 guys to do, and requires little changes on your behalf.

Can you advise, and if it turns out to be true, update the github MD to reflect this?

Or is it better to follow your instructions on all of the copying etc?

Please advise, thanks

**Comment by eneufeld** [comment]
Hi @brettforbes ,
I have no experience with cmder. I will check whether the Git-Bash (that is installed by default if you install git) allows to run the shell script.

**Comment by brettforbes** [comment]
You're a legened @eneufeld , thanks a lot!!
