### ISSUE TITLE
Changing any property in tree editor leads to validation error for "duration"

### ISSUE THREAD

**Issue by sdirix** [eclipse-emfcloud/coffee-editor#363]
## Error description
When changing any value in the tree editor, the user is presented with a validation error for `duration`

![DurationInteger](https://user-images.githubusercontent.com/8998368/117423973-93008b00-af21-11eb-8899-bf87f15290c4.png)

It seems that is only an update issue: Closing and reopening the editor does not show the error anymore.

## How to reproduce
 - Encountered when running the [C++ image](https://github.com/eclipse-emfcloud/coffee-editor/pull/360)
 - Open tree editor (click on `.coffee` file)
 - Select `Workflow > Preheat`
 - Change name to `Preheat 2`

# Expected behavior
There is no invalid validation error for `duration` when updating any value in the tree editor.

**Comment by ndoschek** [comment]
Fixed
