### ISSUE TITLE
Update to GLSP 0.9

### ISSUE THREAD

**Issue by debovema** [eclipse-emfcloud/coffee-editor#375]
Is there a plan to update the GLSP dependencies to version 0.9 ?

From what I can see it has several impacts. For instance in [WorkflowModelFactory](https://github.com/eclipse-emfcloud/coffee-editor/blob/master/backend/plugins/org.eclipse.emfcloud.coffee.workflow.glsp.server.app/src/org/eclipse/emfcloud/coffee/workflow/glsp/server/model/WorkflowModelFactory.java), ModelFactory interface has been replaced with GModelFactory one.

**Comment by eneufeld** [comment]
Hi, 
yes there is a plan. There is a branch witch is mostly ready: https://github.com/eclipse-emfcloud/coffee-editor/tree/ece-demo
