### ISSUE TITLE
Undo api not working properly

### ISSUE THREAD

**Issue by aurelio-pennacchio** [eclipse-emfcloud/coffee-editor#384]
I was trying to extend the coffe-editor in order to implement undo/redo commands when I noticed that the undo command of an add command is not working properly. Basically the model-server return a remove command to the frontend but the command hasn't the indices array feature but instead the objectValues one. This is a issue because the frontend is expecting a indices feature from which it can obtain the index of the object to remove. 
This is how the model-server return a remove command for an add command: 
`{
  "type": "incrementalUpdate",
  "data": {
    "eClass": "http://www.eclipsesource.com/schema/2019/modelserver/command#//Command",
    "type": "remove",
    "owner": {
      "eClass": "http://org/enyr/eu/emfcloud/example/abc#//TFunction",
      "$ref": "file:/home/My2.abc#//@Process.0/@Function.0"
    },
    "feature": "LNode",
    "objectValues": [
      {
        "eClass": "http://org/enyr/eu/emfcloud/example/abc#//TLNode",
        "$ref": "file:/home/My2.abc#//@Process.0/@Function.0/@LNode.2"
      }
    ]
  }
}`

This is how the model-server should return the remove command in order for the frontend to actually being able to remove the element
`{
  "type": "incrementalUpdate",
  "data": {
    "eClass": "http://www.eclipsesource.com/schema/2019/modelserver/command#//Command",
    "type": "remove",
    "owner": {
      "eClass": "http://org/enyr/eu/emfcloud/example/abc#//TFunction",
      "$ref": "file:/home/My2.abc#//@Process.0/@Function.0"
    },
    "feature": "LNode",
    "indices": [
      1
    ]
  }
}`

**Comment by eneufeld** [comment]
Hi @aurelio-pennacchio , 
sorry for the late reply.
This is due to a missing modelserver update.
This should work on the https://github.com/eclipse-emfcloud/coffee-editor/tree/ece-demo branch, though.

**Comment by eneufeld** [comment]
This should work with the latest master. Please reopen if undo still doesn't work for you.

**Comment by aurelio-pennacchio** [comment]
Thank you very much! I'll check out very soon!
