### ISSUE TITLE
Remove/delete does not sync between glsp and tree view

### ISSUE THREAD

**Issue by sgraband** [eclipse-emfcloud/coffee-editor#396]
- [ ] When deleting in GLSP View the tree view is simply not updated -> file reopen does the trick

- [ ] When deleted in the tree view, the notation element is not updated -> glsp view stays the same and breaks, because the two are out of sync

**Comment by eneufeld** [comment]
This should be fixed when https://github.com/eclipse-emfcloud/emfcloud-modelserver/pull/151 is merged, as we can directly apply patches from the modelserver to change the data using https://github.com/martindale/fast-json-patch

**Comment by ndoschek** [comment]
Outdated, will be fixed with #455
