### ISSUE TITLE
Changes via text editor or git reset are not registered

### ISSUE THREAD

**Issue by ndoschek** [eclipse-emfcloud/coffee-editor#406]
When the files(.notation and .coffee) are changed outside the diagram/tree editor or are discarded in the git view, changes are not registered.

Depends on https://github.com/eclipse-emfcloud/emfcloud-modelserver/issues/115

**Comment by eneufeld** [comment]
@ndoschek This would be auto fixed with an update to the latest model server as done by #424 right?

**Comment by ndoschek** [comment]
Yes, exactly!
