### ISSUE TITLE
Tree Editor remove and add of nested objects

### ISSUE THREAD

**Issue by ndoschek** [eclipse-emfcloud/coffee-editor#407]
For the case, that properties can have nested arrays of objects, the tree has to determine if objects were added/removed and the correct commands has to be sent. This is the case for example for the `RAM` array of a `Processor`.

- Tree Editor: double check the retrieval of data differences (not only the feature field, also a valid method to retrieve added and removed objects from the array)
- JsonForms: double check why the array renderer is not accepting a detailed UI schema for the (as a workaround the unwanted columns were disabled via CSS)

**Comment by ndoschek** [comment]
To support investigation, here is a postman collection that includes a valid request to manipulate `RAM` elements.
Please update `$ref` of newly created `RAM` elements if you want to set their value or remove them again.
[Coffee Editor.postman_collection.zip](https://github.com/eclipse-emfcloud/coffee-editor/files/7905225/Coffee.Editor.postman_collection.zip)

**Comment by eneufeld** [comment]
I suggest to handle this after https://github.com/eclipse-emfcloud/emfcloud-modelserver/pull/151 was merged, this would allow us to use a lib like https://github.com/martindale/fast-json-patch to create a patch and send it directly to the modelserver
