### ISSUE TITLE
Tree does not handle setting properties of Processor Dimension

### ISSUE THREAD

**Issue by ndoschek** [eclipse-emfcloud/coffee-editor#408]
Tree does not accept changes of `dimension` properties (height, width, length) in the `processor` element of a `controlUnit`

**Comment by ndoschek** [comment]
To support investigation, here is a postman collection that includes a valid request to manipulate the dimension properties.
[Coffee Editor.postman_collection.zip](https://github.com/eclipse-emfcloud/coffee-editor/files/7905225/Coffee.Editor.postman_collection.zip)

**Comment by eneufeld** [comment]
Should be fixed after https://github.com/eclipse-emfcloud/emfcloud-modelserver/pull/151 see #396 #407
