### ISSUE TITLE
run "./run.sh"  get error : Call to p2 director application failed with exit code 13

### ISSUE THREAD

**Issue by davidxwwang** [eclipse-emfcloud/coffee-editor#416]
lwhen run "./run.sh" on  "Linux version 5.11.0-46-generic (buildd@lgw01-amd64-010) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022" I get the follow error

[INFO] --- tycho-p2-director-plugin:2.2.0:materialize-products (materialize-products) @ org.eclipse.emfcloud.coffee.product ---
[INFO] Installing product org.eclipse.emfcloud.coffee.product.modelserver for environment win32/win32/x86_64 to /home/user/Documents/xrmal_demo/coffee-editor/backend/releng/org.eclipse.emfcloud.coffee.product/target/products/org.eclipse.emfcloud.coffee.product.modelserver/win32/win32/x86_64
Installing org.eclipse.emfcloud.coffee.product.modelserver 0.1.0.202201140223.
Installation failed.
Cannot complete the install because one or more required items could not be found.
	Software being installed: Coffee Model Server 0.1.0.202201140223 (org.eclipse.emfcloud.coffee.product.modelserver 0.1.0.202201140223)
	Missing requirement: Coffee Model Server 0.1.0.202201140223 (org.eclipse.emfcloud.coffee.product.modelserver 0.1.0.202201140223) requires 'org.eclipse.equinox.p2.iu; org.eclipse.emfcloud.modelserver.common [0.7.0.202201070444,0.7.0.202201070444]' but it could not be found
There were errors. See log file: /tmp/tycho1664351365213742223equinox/config/1642126999919.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for org.eclipse.emfcloud.coffee.parent 0.1.0-SNAPSHOT:
[INFO] 
[INFO] org.eclipse.emfcloud.coffee.parent ................. SUCCESS [  0.730 s]
[INFO] org.eclipse.emfcloud.coffee.target ................. SUCCESS [  0.621 s]
[INFO] org.eclipse.emfcloud.coffee.modelserver.app ........ SUCCESS [  5.571 s]
[INFO] org.eclipse.emfcloud.coffee.codegen.product ........ FAILURE [ 58.944 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:47 min
[INFO] Finished at: 2022-01-14T10:26:04+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-director-plugin:2.2.0:materialize-products (materialize-products) on project org.eclipse.emfcloud.coffee.product: Installation of product org.eclipse.emfcloud.coffee.product.modelserver for environment win32/win32/x86_64 failed: Call to p2 director application failed with exit code 13. Program arguments were: [-metadataRepository, file:/home/user/Documents/xrmal_demo/coffee-editor/backend/releng/org.eclipse.emfcloud.coffee.product/target/,file:/home/user/Documents/xrmal_demo/coffee-editor/backend/releng/org.eclipse.emfcloud.coffee.product/target/targetPlatformRepository/, -artifactRepository, file:/home/user/Documents/xrmal_demo/coffee-editor/backend/releng/org.eclipse.emfcloud.coffee.product/target/,file:/resolution-context-artifacts@%252Fhome%252Fuser%252FDocuments%252Fxrmal_demo%252Fcoffee-editor%252Fbackend%252Freleng%252Forg.eclipse.emfcloud.coffee.product,file:/home/user/Documents/xrmal_demo/coffee-editor/backend/releng/org.eclipse.emfcloud.coffee.product/target/,file:/home/user/Documents/xrmal_demo/coffee-editor/backend/plugins/org.eclipse.emfcloud.coffee.modelserver.app/target/,file:/home/user/.m2/repository/, -installIU, org.eclipse.emfcloud.coffee.product.modelserver, -destination, /home/user/Documents/xrmal_demo/coffee-editor/backend/releng/org.eclipse.emfcloud.coffee.product/target/products/org.eclipse.emfcloud.coffee.product.modelserver/win32/win32/x86_64, -profile, DefaultProfile, -profileProperties, org.eclipse.update.install.features=true, -roaming, -p2.os, win32, -p2.ws, win32, -p2.arch, x86_64]. -> [Help 1]

**Comment by eneufeld** [comment]
Hi, thank you for the report.
The master branch is unfortunately outdated. We will decided soon when and how to integrate an update. You can find the ongoing work on the [ece_demo](https://github.com/eclipse-emfcloud/coffee-editor/tree/ece-demo) branch.
Sorry for the inconvenience.

**Comment by davidxwwang** [comment]
thank you very much

**Comment by eneufeld** [comment]
The master branch was now updated. Can you double check whether it works for you now?

**Comment by eneufeld** [comment]
Please reopen if issue persists

**Comment by gdaniel** [comment]
Hi,

I have a similar issue: the build fails on `org.eclipse.emfcloud.coffee.codegen.product`, with the following error message

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for org.eclipse.emfcloud.coffee.parent 0.1.0-SNAPSHOT:
[INFO]
[INFO] org.eclipse.emfcloud.coffee.parent ................. SUCCESS [  0.132 s]
[INFO] org.eclipse.emfcloud.coffee.target ................. SUCCESS [  0.124 s]
[INFO] org.eclipse.emfcloud.coffee.model .................. SUCCESS [  1.547 s]
[INFO] org.eclipse.emfcloud.coffee.common ................. SUCCESS [  0.338 s]
[INFO] org.eclipse.emfcloud.coffee.workflow.generator ..... SUCCESS [  0.189 s]
[INFO] org.eclipse.emfcloud.coffee.workflow.generator.cpp . SUCCESS [  3.623 s]
[INFO] org.eclipse.emfcloud.coffee.codegen.cpp.application  SUCCESS [  0.314 s]
[INFO] org.eclipse.emfcloud.coffee.workflow.generator.java  SUCCESS [  0.761 s]
[INFO] org.eclipse.emfcloud.coffee.codegen.java.application SUCCESS [  0.263 s]
[INFO] org.eclipse.emfcloud.coffee.modelserver ............ SUCCESS [  0.648 s]
[INFO] org.eclipse.emfcloud.coffee.modelserver.app ........ SUCCESS [  0.283 s]
[INFO] org.eclipse.emfcloud.coffee.modelserver.feature .... SUCCESS [  0.083 s]
[INFO] org.eclipse.emfcloud.coffee.workflow ............... SUCCESS [  0.143 s]
[INFO] org.eclipse.emfcloud.coffee.workflow.analyzer ...... SUCCESS [  0.081 s]
[INFO] org.eclipse.emfcloud.coffee.workflow.dsl ........... SUCCESS [  5.828 s]
[INFO] org.eclipse.emfcloud.coffee.workflow.analyzer.coffee SUCCESS [  0.329 s]
[INFO] org.eclipse.emfcloud.coffee.workflow.analyzer.application SUCCESS [  0.399 s]
[INFO] org.eclipse.emfcloud.coffee.workflow.dsl.ide ....... SUCCESS [  5.224 s]
[INFO] org.eclipse.emfcloud.coffee.workflow.glsp.server ... SUCCESS [  0.715 s]
[INFO] org.eclipse.emfcloud.coffee.workflow.glsp.server.app SUCCESS [  0.303 s]
[INFO] org.eclipse.emfcloud.coffee.workflow.glsp.server.feature SUCCESS [  0.081 s]
[INFO] org.eclipse.emfcloud.coffee.codegen.product ........ FAILURE [  6.563 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  47.409 s
[INFO] Finished at: 2022-04-07T14:09:00+02:00
[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-director-plugin:2.2.0:materialize-products (materialize-products) on project org.eclipse.emfcloud.coffee.product: Installation of product org.eclipse.emfcloud.coffee.product.workflow.analyzer for environment win32/win32/x86_64 failed: Call to p2 director application failed with exit code 13. Program arguments were:
```

There is also a missing requirement error in the logs:
```
Installation failed.
Cannot complete the install because one or more required items could not be found.
        Software being installed: Workflow Analyzer 0.1.0 (org.eclipse.emfcloud.coffee.product.workflow.analyzer 0.1.0)
        Missing requirement: Workflow Analyzer 0.1.0 (org.eclipse.emfcloud.coffee.product.workflow.analyzer 0.1.0) requires 'org.eclipse.equinox.p2.iu; org.eclipse.emfcloud.modelserver.common [0.7.0.202204071136,0.7.0.202204071136]' but it could not be found
```

**Context**
I am using Windows 10 with Maven 3.8.4 and Java 11. I followed the installation instructions and got the error when running run.sh.

If this is the master branch that is outdated can you point me to a more recent branch I could use?

Let me know if you need any additional information

**Comment by eneufeld** [comment]
@gdaniel we will double check

**Comment by eneufeld** [comment]
@gdaniel can you test this PR? https://github.com/eclipse-emfcloud/coffee-editor/pull/439

**Comment by gdaniel** [comment]
Hi @eneufeld,

The PR fixed the maven build, and I can successfully build the backend, thanks!
I now have an error in the yarn build for the frontend, I paste the error logs below, but let me know if you want me to open a new issue for this new error.

```
coffee-workflow-glsp-editor: $ tsc && yarn run lint
coffee-workflow-glsp-editor: src/browser/diagram/workflow-diagram-configuration.ts(25,48): error TS2307: Cannot find module 'coffee-workflow-glsp' or its corresponding type declarations.
coffee-workflow-glsp-editor: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
coffee-workflow-glsp-editor: error Command failed with exit code 2.
coffee-workflow-glsp-editor: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
coffee-workflow-glsp-editor: error Command failed with exit code 2.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run prepare
lerna ERR! error Command failed with exit code 2.
lerna ERR! error Command failed with exit code 2.
lerna ERR!
lerna ERR! yarn run v1.22.18
lerna ERR! $ yarn run clean && yarn run build
lerna ERR! $ rimraf lib
lerna ERR! $ tsc && yarn run lint
lerna ERR! src/browser/diagram/workflow-diagram-configuration.ts(25,48): error TS2307: Cannot find module 'coffee-workflow-glsp' or its corresponding type declarations.
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR!
lerna ERR!     at C:\Users\zelus\Documents\Dev\EMF_Cloud\coffee-editor-test\coffee-editor\web\node_modules\execa\index.js:236:11
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
coffee-welcome-page: src/browser/welcome-page-widget.tsx(20,56): error TS2307: Cannot find module 'coffee-cpp-extension/lib/browser/command-contribution' or its corresponding type declarations.
coffee-welcome-page: src/browser/welcome-page-widget.tsx(21,57): error TS2307: Cannot find module 'coffee-java-extension/lib/browser/command-contribution' or its corresponding type declarations.
coffee-welcome-page: src/browser/welcome-page-widget.tsx(22,33): error TS2307: Cannot find module 'coffee-workflow-analyzer/lib/browser/command-contribution' or its corresponding type declarations.
coffee-welcome-page: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
coffee-welcome-page: error Command failed with exit code 2.
coffee-welcome-page: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
coffee-welcome-page: error Command failed with exit code 2.
Error: Command failed: yarn run prepare
error Command failed with exit code 2.
error Command failed with exit code 2.

yarn run v1.22.18
$ yarn run clean && yarn run build
$ rimraf lib
$ tsc && yarn run lint
src/browser/diagram/workflow-diagram-configuration.ts(25,48): error TS2307: Cannot find module 'coffee-workflow-glsp' or its corresponding type declarations.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at C:\Users\zelus\Documents\Dev\EMF_Cloud\coffee-editor-test\coffee-editor\web\node_modules\execa\index.js:236:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 2,
  killed: false,
  stdout: 'yarn run v1.22.18\n' +
    '$ yarn run clean && yarn run build\n' +
    '$ rimraf lib\n' +
    '$ tsc && yarn run lint\n' +
    "src/browser/diagram/workflow-diagram-configuration.ts(25,48): error TS2307: Cannot find module 'coffee-workflow-glsp' or its corresponding type declarations.\r\n" +
    'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: 'error Command failed with exit code 2.\n' +
    'error Command failed with exit code 2.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run prepare',
  timedOut: false,
  exitCode: 1
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
