### ISSUE TITLE
error on "macOS big Sur version11 "  when run ".run.sh -r" : theia: command not found and x-www-browser cannot found

### ISSUE THREAD

**Issue by davidxwwang** [eclipse-emfcloud/coffee-editor#418]
yilia@fengjiadeMacBook-Pro coffee-editor-ece-demo % ./run.sh  -r
[16:15:55.3N] Evaluate Options... 
  Do not build Backend (-b)
  Do not copy Backend (-c)
  Do not remove yarn.lock  (-ff)
  Do not build Frontend (-f)
  Run Frontend (-r)
yarn run v1.22.10
$ cd browser-app && yarn start
$ export WF_CONFIG_LSP=localhost:5017 && theia start --WORKFLOW_NOTATION_LSP=5008 --hostname=0.0.0.0 --port=3000 --root-dir=../../backend/examples/SuperBrewer3000 --plugins=local-dir:./plugins
/bin/sh: theia: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by eneufeld** [comment]
Hi @davidxwwang , 
before you call `./run.sh -r` you need to run `./run.sh -f`.
Does the error prevail after the `./run.sh -f` ?

**Comment by eneufeld** [comment]
Please feel free to reopen if issue persists.
