### ISSUE TITLE
Marquee tool does not work

### ISSUE THREAD

**Issue by eneufeld** [eclipse-emfcloud/coffee-editor#420]
![marquee](https://user-images.githubusercontent.com/1176277/150304077-a1fed076-38bd-4a0e-9c64-32d1da500c09.gif)

**Comment by eneufeld** [comment]
@tortmayr @ndoschek any idea what might cause this?

**Comment by tortmayr** [comment]
@eneufeld I opened a PR to fix this.
While i was on it, I also added some other minor changes (metadata update & package renaming)

**Comment by eneufeld** [comment]
fixed with 03539ebfb62ede5454858e67887231458ab180a7
