### ISSUE TITLE
Update Feedback text on deployed version

### ISSUE THREAD

**Issue by eneufeld** [eclipse-emfcloud/coffee-editor#427]
When the coffee editor is loading on the kubernetes instance, the first step is to prepare the container.
We should improve the feedback to the user to better differentiate between this step and the actual loading of the coffee editor and thus theia.

**Comment by koegel** [comment]
Not exactly sure what you mean, but imho this is the case already. There is a loading indicator on the landing page and once the user is forwarded to the instance there is a new loading indicator for Theia.

**Comment by eneufeld** [comment]
This will be fixed by moving to the Theia-cloud deployment
