### ISSUE TITLE
Missing dependency 'Slf4j simple'

### ISSUE THREAD

**Issue by davidxwwang** [eclipse-emfcloud/coffee-editor#431]
when l download the master branch of latest "coffee-editor" on windows ,then run the "run.sh" shell, build successfully, but l get the following errors(the older version is fine): 

E:\coffee-editor-master\web\coffee-server\server\model\x86_64>java -version
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

E:\coffee-editor-master\web\coffee-server\server\model\x86_64>java -jar plugins\org.eclipse.equinox.launcher_1.6.300.v20210813-1054.jar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-02-25 19:53:22.707:INFO::main: Logging initialized @3040ms to org.eclipse.jetty.util.log.StdErrLog

Missing dependency 'Slf4j simple'. Add the dependency.

pom.xml:
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>1.7.30</version>
</dependency>

build.gradle:
compile "org.slf4j:slf4j-simple:1.7.30"

Find the latest version here:
https://search.maven.org/search?q=g%3Aorg.slf4j+AND+a%3Aslf4j-simple

Missing dependency 'Slf4j simple with Provider'. Add the dependency.

pom.xml:
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>1.8.0-beta4</version>
</dependency>

build.gradle:
compile "org.slf4j:slf4j-api:1.8.0-beta4"

Find the latest version here:
https://search.maven.org/search?q=g%3Aorg.slf4j+AND+a%3Aslf4j-api

Missing dependency 'Slf4j simple with Provider'. Add the dependency.

pom.xml:
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>1.8.0-beta4</version>
</dependency>

build.gradle:
compile "org.slf4j:slf4j-simple:1.8.0-beta4"

Find the latest version here:
https://search.maven.org/search?q=g%3Aorg.slf4j+AND+a%3Aslf4j-simple

Visit https://javalin.io/documentation#logging if you need more help

E:\coffee-editor-master\web\coffee-server\server\model\x86_64>

even  l add the required dependencies in  pom.xml in  org.eclipse.emfcloud.coffee.parent, still get the errors.

**Comment by eneufeld** [comment]
Thank you for the report, we will check this.

**Comment by eneufeld** [comment]
Hi @davidxwwang, 
yes I can see the same behavior. I agree that this log is annoying. The missing slf4j leads to missing logs.
Thank you for the report.
