### ISSUE TITLE
Update dependencies in org.eclipse.emfcloud.coffee.target.target

### ISSUE THREAD

**Issue by felixalleweldt** [eclipse-emfcloud/coffee-editor#442]
The application is broken since the 2022-04-11 update.

One dependency in 

backend/releng/org.eclipse.emfcloud.coffee.target/org.eclipse.emfcloud.coffee.target.target

cannot be solved anymore.

`Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/3.0.0/maven-shade-plugin-3.0.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/3.0.0/maven-shade-plugin-3.0.0.jar (113 kB at 1.8 MB/s)
[INFO] Computing target platform for MavenProject: org.eclipse.emfcloud.coffee:org.eclipse.emfcloud.coffee.product:0.1.0-SNAPSHOT @ /coffee-editor/backend/releng/org.eclipse.emfcloud.coffee.product/pom.xml
[ERROR] Failed to resolve target definition /coffee-editor/backend/releng/org.eclipse.emfcloud.coffee.target/org.eclipse.emfcloud.coffee.target.target: Failed to load p2 metadata repository from location https://download.eclipse.org/modeling/tmf/xtext/updates/milestones/S202110010541/: No repository found at https://download.eclipse.org/modeling/tmf/xtext/updates/milestones/S202110010541. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
Error: error building at STEP "RUN ./run.sh -bcf &&     cp ./web/favicon.ico ./web/browser-app/lib": error while running runtime: exit status 1`

**Comment by eneufeld** [comment]
@felixalleweldt, 
thank you for the report. 
Can you check whether https://github.com/eclipse-emfcloud/coffee-editor/pull/439 works for you?

**Comment by felixalleweldt** [comment]
Hello @eneufeld ,

yes, branch fix/437 let me compile the project.

Thank you

**Comment by eneufeld** [comment]
Branch is merged
