### ISSUE TITLE
Coffee-related icons not shown in the editor

### ISSUE THREAD

**Issue by gdaniel** [eclipse-emfcloud/coffee-editor#445]
This happens on a local build or using the docker image locally.

Coffee-related icons aren't displayed in the editor, this includes the purple coffee icon for the superbrewer.coffee file, but also all the icons in the tree editor. On the other hand the [online coffee-editor demo](https://eclipsesource.com/coffee-editor) has these icons.

I've seen in the code that the editor is using codicons, is there anything I need to configure to make it work? I didn't see any error in the logs.

Note that I am not sure this is a coffee-editor specific issue, other icons like .gitignore files or pom.xml aren't displayed in my local build neither (while they are correctly displayed on the online demonstration).

Screenshot of the editor without the icons

![missing-icons](https://user-images.githubusercontent.com/6516281/170276912-f82ce20e-6367-4c85-9326-829a6a3cf2df.PNG)

**Comment by eneufeld** [comment]
Hi @gdaniel  you are on master?
For me icons work.
Did you check the debug tools whether there are any error logs?

**Comment by gdaniel** [comment]
Hi @eneufeld,
I checked on different browsers and the issue was on my side. For some reason I had to clear chrome's cache and everything worked as expected.
Sorry for the inconvenience

**Comment by eneufeld** [comment]
Thank you for the update!
