### ISSUE TITLE
After emfcloud related updates, command operations are failing on coffee tree editor(superbrewer3000.coffee)

### ISSUE THREAD

**Issue by mishaltripathi** [eclipse-emfcloud/coffee-editor#446]
Hi,

After latest commit/updates of emfcloud on coffee editor, I am not able to perform any operation(add/set/delete) on coffee tree editor (superbrewer3000.coffee) and getting below error in my console.

![error_log1](https://user-images.githubusercontent.com/45622489/170825162-a092e608-c5e5-4dd2-9c78-ccf941b449dc.png)
![error_log2](https://user-images.githubusercontent.com/45622489/170825171-7add9e65-11c4-4164-adef-5c17b6cc2cc4.png)

While it was working before the latest updates. Please have a look into it.

Thanks,
Mishal

**Comment by eneufeld** [comment]
Hi @mishaltripathi ,

thank you for your report. We did not encounter this error yet.
Did you try running `git clean -dxf` and then reinstalling and rebuilding everything again? Maybe you have a weird state in your `node_modules`?
Please let us know.

Best,
Eugen

**Comment by mishaltripathi** [comment]
Thanks @eneufeld for your response. I tried your suggestion but didn't help. I also debugged it and found that payload doesn't contain required data to create command at decoding part of DefaultJsonCodec(backend) where its expected to load json resource from payload and return command object.

**Comment by eneufeld** [comment]
Hi @mishaltripathi ,
I tried again and build from root. I can reproduce your error now.
I'm currently updating the whole edit functionality to use json patches. So I would suggest to focus on this update as it will give us more features.

**Comment by Deel96** [comment]
Hi,
I encountered the same problem in the last days. I also tried different commits but always get the same error.
Is it known which version is "working"?

I also tried the available 2 releases, which I couldn't even get building.

```
yarn run v1.22.19
$ theia start --WORKFLOW_NOTATION_LSP=5008 --WF_LSP=5017 --port=3000 --loglevel=debug --root-dir=../../backend/examples/ --loglevel=debug  --plugins=local-dir:./plugins --hostname 0.0.0.0
/bin/sh: 1: theia: not found
error Command failed with exit code 127.
```

**Comment by koegel** [comment]
> Hi, I encountered the same problem in the last days. I tried older versions but always got a "deal breaking" bugs
> 
> Editing works partially with commits [4ebc695](https://github.com/eclipse-emfcloud/coffee-editor/commit/4ebc6953d3afeb937c5b59fee30225cf9ceabda1) , [8456e17](https://github.com/eclipse-emfcloud/coffee-editor/commit/8456e17b6cc4e75a8a001038622cdedc368bbaf5) (After updating dependencies of xtext.sdk.feature.group for build) where I could change the properties of the machine. But most properties for example of the ControlUnit don't persist when going to another element.

i believe this comment was also posted as part of an ongoing discussion in Discourse, so I am closing this issue. Feel free to reopen if you disagree,
