### ISSUE TITLE
Workflow  Analyzer Editor is failing 

### ISSUE THREAD

**Issue by tortmayr** [eclipse-emfcloud/coffee-editor#478]
With the update to Theia 1.29(https://github.com/eclipse-emfcloud/coffee-editor/pull/470) the Workflow Analyzer Editor extension now seems to be failing on activation:

Activating extension 'coffee-workflow-analyzer-editor' failed: Cannot find module 'vscode-jsonrpc' Require stack: - /tmp/vscode-unpacked/coffee-workflow-analyzer-editor-0.1.0.vsix/extension/out/extension.js - /home/tobias/Git/OpenSource/emfcloud/coffee-editor/client/node_modules/@theia/core/lib/node/dynamic-require.js - /home/tobias/Git/OpenSource/emfcloud/coffee-editor/client/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js - /home/tobias/Git/OpenSource/emfcloud/coffee-editor/client/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host.js

**Comment by eneufeld** [comment]
Is this with or without the Java 17 update?

**Comment by tortmayr** [comment]
Happens in both cases. Also the error message indicates that it rather is a client side problem and it should not be affected by the Java upadte

**Comment by tortmayr** [comment]
Looks like this was introduced with this change in https://github.com/eclipse-emfcloud/coffee-editor/pull/470 :
```diff
-"package": "vsce package && copyfiles coffee-workflow-analyzer-editor-0.1.0.vsix ../browser-app/plugins/"
+"package": "vsce package --yarn && copyfiles coffee-workflow-analyzer-editor-0.1.0.vsix ../browser-app/plugins/"
```
However, simply reverting the change results in a build error

**Comment by sgraband** [comment]
FYI: This change was neccessary as otherwise the build with node 16 would not work.

Maybe this error (or a similar one) is then still happening, but is just ignored/skipped?

**Comment by tortmayr** [comment]
>Maybe this error (or a similar one) is then still happening, but is just ignored/skipped?

For me the Workflow LSP does no longer work properly (only syntax highlighting  and basic vscode auto completion) which makes sense since the extension providing the language server failed to activate.
