### ISSUE TITLE
Project explorer icons are missing in docker build

### ISSUE THREAD

**Issue by sgraband** [eclipse-emfcloud/coffee-editor#481]
![MissingIcons](https://user-images.githubusercontent.com/51790726/204277182-be407ef6-88ae-4894-9077-3332066c3c2e.png)

In the normal browser build everything seems to be fine.

**Comment by tortmayr** [comment]
Seems like there even is an an option to define this in the  application `package.json`:
https://github.com/eclipse-theia/theia/discussions/11890#discussioncomment-4194288

**Comment by ndoschek** [comment]
> Seems like there even is an an option to define this in the application `package.json`: [eclipse-theia/theia#11890 (reply in thread)](https://github.com/eclipse-theia/theia/discussions/11890#discussioncomment-4194288)

Yes that's true, we should then decide which way we want to define such defaults - either in the package.json directory or in the existing workspace settings. For example we have an existing workspace settings to disable auto save preference.
