### ISSUE TITLE
Coffee Editor, diagram does not open

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-emfcloud/coffee-editor#503]
started here: https://eclipsesource.com/coffee-editor

diagram is empty and I get this error:

[GLSP-Server] Could not process message:ActionMessage [action=requestModel, clientId=workflow-diagram-notation:file:///coffee-editor/client/workspace/SuperBrewer3000/superbrewer3000.notation]

**Comment by JonasHelming** [comment]
@koegel

**Comment by shinesamjacob** [comment]
Even i too get this error occasionally, not sure what is the root cause

**Comment by sgraband** [comment]
This is the result of #494 and i currently investigate it.
